### PR TITLE
Added some examples from Chapter 4.6 in the manual.

### PR DESCRIPTION
**Pull request by tpapp**
Not all of them, but this should demonstrate how to use the interface.

### CODE REVIEW

**Comment by KristofferC** [comment]
Great!

In the long term, we should perhaps remove this repo and transition to generate these examples in the PGFPlotsX.jl documentation directly. But for now, good to have it here.

**Comment by KristofferC** [comment]
The time it takes to download texlive on Travis is really annoying. You don't happen to know some smaller version we could use that would still let us have access to `lualatex` and PGFPlots?

**Comment by KristofferC** [comment]
Passes locally.

**Comment by tpapp** [comment]
Regarding the download time: `texlive-latex-base` should have `lualatex`, and `texlive-pictures` has `pgflots`, so that may be sufficient for core testing. But that's on Ubuntu 17.10, I don't know how that works with `ppa:jonathonf/texlive-2016` though.

A Docker image, either a custom one or one of the prebuilt TeXLive ones, with recent Ubuntu, could be a [solution](https://docs.travis-ci.com/user/docker/). But it is a bit of work to setup.

**Pull request merged**
